version: "3"
services:
  server:
    image: node:current-alpine
    ports:
      - 0.0.0.0:80:3001
    container_name: "server"
    working_dir: '/opt'
    volumes:
      - ./:/opt
    command: "npm start"
  
